### ISSUE TITLE
无法连接到openai

### ISSUE THREAD

**Issue by QiranYC** [Suxmx/nonebot_plugin_chatgpt_on_qq#17]
使用了代理但是仍然无法连接

04-12 20:41:30 [DEBUG] nonebot | Running PreProcessors...
04-12 20:41:30 [DEBUG] nonebot | Checking for matchers in priority 1...
04-12 20:41:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_chatgpt_on_qq)
04-12 20:41:31 [DEBUG] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_chatgpt_on_qq)
04-12 20:41:31 [DEBUG] nonebot | Running handler Dependent(call=_)
04-12 20:41:31 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_chatgpt_on_qq) running complete
04-12 20:41:31 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_chatgpt_on_qq) failed.
Traceback (most recent call last):
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\aiohttp\client.py", line 508, in _request
    req = self._request_class(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /chat/completions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\bot\yuni_dev\nonebot\src\plugins\nonebot_plugin_chatgpt_on_qq\chatGPT.py", line 73, in ask
    completion = await self._get_completion(user_input, temperature)
  File "D:\bot\yuni_dev\nonebot\src\plugins\nonebot_plugin_chatgpt_on_qq\chatGPT.py", line 87, in _get_completion
    return await openai.ChatCompletion.acreate(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\bot\yuni_dev\nonebot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\yuni_dev\nonebot\src\plugins\nonebot_plugin_chatgpt_on_qq\__init__.py", line 100, in _
    answer = await userConversation.ask(userInput)
  File "D:\bot\yuni_dev\nonebot\src\plugins\nonebot_plugin_chatgpt_on_qq\chatGPT.py", line 78, in ask
    raise ConnectionError
ConnectionError
04-12 20:41:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_bing_chat.common)
04-12 20:41:31 [DEBUG] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_bing_chat.common)
04-12 20:41:31 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_bing_chat.common) running complete
04-12 20:41:31 [DEBUG] nonebot | Stop event propagation
04-12 20:41:31 [DEBUG] nonebot | Checking for matchers completed

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/231462301-937d637d-798d-45c1-bfe0-d7bd11263b26.png)
如果确认配置文件里的代理和本身的代理都没问题的话  
你的报错和 #10 的很像 都是Invalid URL
![0~EL`0HXU~JOJS677$HX2(8](https://user-images.githubusercontent.com/33772816/231462533-fff8c5be-c729-471b-bc8f-e787051238f1.png)
@rick23318 他的解决方案是直接找到了openai库的代码 在`/chat/completions`前面加上了https://api.openai.com/v1的前缀你可以试试

**Comment by Both-WH** [comment]
我的则是在“/talk <>”命令时显示连接错误，不知道该怎么弄，因为我还是个小白，摸索到这里已经被掏空了身体了（吐血）
![image](https://user-images.githubusercontent.com/116142703/232233787-110dd658-810e-4b85-8f92-2dfefa6f5e31.png)
不知道有些该怎么设置

**Comment by Suxmx** [comment]
把openai_proxy中的http://  以及最后的/去掉试试

**Comment by Suxmx** [comment]
> 我的则是在“/talk <>”命令时显示连接错误，不知道该怎么弄，因为我还是个小白，摸索到这里已经被掏空了身体了（吐血） ![image](https://user-images.githubusercontent.com/116142703/232233787-110dd658-810e-4b85-8f92-2dfefa6f5e31.png) 不知道有些该怎么设置，如果可以，佬能给个联系方式吗？TAT

不好意思 没看到最后一句
qq424504326
明天考试可能回的不及时

**Comment by Peins** [comment]
> 我的则是在“/talk <>”命令时显示连接错误，不知道该怎么弄，因为我还是个小白，摸索到这里已经被掏空了身体了（吐血） ![image](https://user-images.githubusercontent.com/116142703/232233787-110dd658-810e-4b85-8f92-2dfefa6f5e31.png) 不知道有些该怎么设置，如果可以，佬能给个联系方式吗？TAT

key泄露了，快删掉，打码，换api的key

**Comment by Both-WH** [comment]
> > 我的则是在“/talk <>”命令时显示连接错误，不知道该怎么弄，因为我还是个小白，摸索到这里已经被掏空了身体了（吐血） ![image](https://user-images.githubusercontent.com/116142703/232233787-110dd658-810e-4b85-8f92-2dfefa6f5e31.png) 不知道有些该怎么设置，如果可以，佬能给个联系方式吗？TAT
> 
> key泄露了，快删掉，打码，换api的key

额，其实问题不大，反正号是买的，马上把图删了

**Comment by Suxmx** [comment]
所以都解决了吗... 怎么都没有反馈()
