### ISSUE TITLE
连接openai时后台报错，聊天窗口没有输出信息

### ISSUE THREAD

**Issue by Earmo** [Suxmx/nonebot_plugin_chatgpt_on_qq#18]
```
04-23 03:00:51 [SUCCESS] nonebot | OneBot V11 1464331775 | [message.group.normal]: Message 514990020 from 1148409172@[群:162918419] "大书库 什么是猫娘"

04-23 03:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)

04-23 03:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)

04-23 03:00:51 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete

04-23 03:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.nonebot_plugin_chatgpt_on_qq-main2)

04-23 03:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)

04-23 03:00:51 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete

04-23 03:00:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)

04-23 03:00:51 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete

04-23 03:00:51 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete

04-23 03:00:51 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_chatgpt_on_qq-main2) running complete

04-23 03:00:51 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.nonebot_plugin_chatgpt_on_qq-main2) failed.

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 588, in arequest_raw

    result = await session.request(**request_kwargs)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 492, in _request

    req = self._request_class(

  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__

    self.update_host(url)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 366, in update_host

    raise InvalidURL(url)

aiohttp.client_exceptions.InvalidURL: /chat/completions


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_chatgpt_on_qq-main2/chatGPT.py", line 73, in ask

    completion = await self._get_completion(user_input, temperature)

  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_chatgpt_on_qq-main2/chatGPT.py", line 87, in _get_completion

    return await openai.ChatCompletion.acreate(

  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate

    return await super().acreate(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate

    response, _, api_key = await requestor.arequest(

  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 300, in arequest

    result = await self.arequest_raw(

  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 605, in arequest_raw

    raise error.APIConnectionError("Error communicating with OpenAI") from e

openai.error.APIConnectionError: Error communicating with OpenAI


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/zhenxun_bot/bot.py", line 21, in <module>

    nonebot.run()

  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run

    get_driver().run(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run

    uvicorn.run(

  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run

    server.run()

  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run

    return asyncio.run(self.serve(sockets=sockets))

  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher

    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)

> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher

    await matcher.run(bot, event, state, stack, dependency_cache)

  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run

    await self.simple_run(bot, event, state, stack, dependency_cache)

  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run

    await handler(

  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__

    return await cast(Callable[..., Awaitable[R]], self.call)(**values)

  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_chatgpt_on_qq-main2/__init__.py", line 66, in _

    answer = await newConversation.ask(userInput)

  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_chatgpt_on_qq-main2/chatGPT.py", line 78, in ask

    raise ConnectionError

ConnectionError
```

![image](https://user-images.githubusercontent.com/42935502/233802188-a8dba285-de7c-497f-a5ee-59ea019b5dc6.png)

配置如下
![image](https://user-images.githubusercontent.com/42935502/233802273-6cf78e4c-c89f-480a-85ce-fe3560dccefd.png)

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/233815836-8a11a943-1b56-4193-bb27-d4a2d133d964.png)
感觉最近好多这个报错啊
可以试试里面的解决方案
#17

**Comment by Suxmx** [comment]
安装之后有成功对话过吗

**Comment by Earmo** [comment]
> ![image](https://user-images.githubusercontent.com/33772816/233815836-8a11a943-1b56-4193-bb27-d4a2d133d964.png) 感觉最近好多这个报错啊 可以试试里面的解决方案 #17

删除代理的协议和后缀/吗，这个试过了，不行

**Comment by Earmo** [comment]
> 安装之后有成功对话过吗

指令是没问题的，但是连接openai不行
![image](https://user-images.githubusercontent.com/42935502/233819503-9d7aade7-be87-4c34-849d-e3d6daf9f727.png)

**Comment by Suxmx** [comment]
> > ![image](https://user-images.githubusercontent.com/33772816/233815836-8a11a943-1b56-4193-bb27-d4a2d133d964.png) 感觉最近好多这个报错啊 可以试试里面的解决方案 #17
> 
> 删除代理的协议和后缀/吗，这个试过了，不行

不是 是改openai里的源码hhh 但是我没遇到过 所以感觉这个问题很玄学

**Comment by Earmo** [comment]
> > > ![image](https://user-images.githubusercontent.com/33772816/233815836-8a11a943-1b56-4193-bb27-d4a2d133d964.png) 感觉最近好多这个报错啊 可以试试里面的解决方案 #17
> > 
> > 
> > 删除代理的协议和后缀/吗，这个试过了，不行
> 
> 不是 是改openai里的源码hhh 但是我没遇到过 所以感觉这个问题很玄学
> 
> > ![image](https://user-images.githubusercontent.com/33772816/231462301-937d637d-798d-45c1-bfe0-d7bd11263b26.png) 如果确认配置文件里的代理和本身的代理都没问题的话 你的报错和 #10 的很像 都是Invalid URL ![image](https://user-images.githubusercontent.com/33772816/231463548-34f637b5-5879-48a7-9a96-7560411e4d25.png)
> > ![0EL`0HXUJOJS677$HX2(8](https://user-images.githubusercontent.com/33772816/231463174-4a04401b-ed5f-4f2e-99bb-be42ccc89249.png)
> > @rick23318 他的解决方案是直接找到了openai库的代码 在`/chat/completions`前面加上了[https://api.openai.com/v1的前缀你可以试试](https://api.openai.com/v1%E7%9A%84%E5%89%8D%E7%BC%80%E4%BD%A0%E5%8F%AF%E4%BB%A5%E8%AF%95%E8%AF%95)

这个可以👍

**Comment by Suxmx** [comment]
解决了？

**Comment by Earmo** [comment]
> 解决了？

是的

**Comment by Suxmx** [comment]
ok

**Comment by F1Justin** [comment]
我也遇到同样的问题，在加上了https://api.openai.com/v1的前缀以及删去代理的https://之后运行成功了

**Comment by Suxmx** [comment]
> 我也遇到同样的问题，在加上了[https://api.openai.com/v1的前缀以及删去代理的https://之后运行成功了](https://api.openai.com/v1%E7%9A%84%E5%89%8D%E7%BC%80%E4%BB%A5%E5%8F%8A%E5%88%A0%E5%8E%BB%E4%BB%A3%E7%90%86%E7%9A%84https://%E4%B9%8B%E5%90%8E%E8%BF%90%E8%A1%8C%E6%88%90%E5%8A%9F%E4%BA%86)
好诡异...总不能是openai库出问题了吧...
