### ISSUE TITLE
导入插件后报错

### ISSUE THREAD

**Issue by QiranYC** [Suxmx/nonebot_plugin_chatgpt_on_qq#5]
未安装其他任何插件的Nonebot2在导入该插件后发生如下报错

03-19 18:08:40 [ERROR] nonebot | Failed to import "nonebot_plugin_chatgpt_on_qq"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Yuche\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot_plugin_chatgpt_on_qq\__init__.py", line 12, in <module>
    from .conversation import Conversation, GroupPanel
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot_plugin_chatgpt_on_qq\conversation.py", line 10, in <module>
    from .chatGPT import ChatGPTBot
  File "D:\bot\bot\yuni\.venv\lib\site-packages\nonebot_plugin_chatgpt_on_qq\chatGPT.py", line 10, in <module>
    plugin_config = Config.parse_obj(get_driver().config.dict())
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
history_max
  value is not a valid integer (type=type_error.integer)

**Comment by Suxmx** [comment]
看起来是hittory_max环境变量错误了 能截个图看看你设置了什么吗？

**Comment by QiranYC** [comment]
> 

![屏幕截图 2023-03-19 182630](https://user-image.githubusercontent.com/97454402/226169269-8fe7ff33-936f-4a54-acf2-b4a4612ae7d0.png)

**Comment by QiranYC** [comment]
好吧，突然反应过来，好像把注释也照搬了，抱歉

**Comment by QiranYC** [comment]
建议在文档中给（）前加#

**Comment by Suxmx** [comment]
okk

**Comment by QiranYC** [comment]
感谢
